// Site metinleri. HTML'deki varsayılan içerik Türkçedir; dil değişince buradan doldurulur.
// "_html" ile biten anahtarlar innerHTML olarak yazılır.
export const METINLER = {
  tr: {
    "meta.title": "NeraHom — Akıllı kombi termostatı",
    "meta.desc": "Pilli oda sensörü, kombi rölesi ve mobil uygulamadan oluşan, internet kesilse de çalışan akıllı ısıtma sistemi.",
    "nav.ekran": "Ekran", "nav.sistem": "Sistem", "nav.claude": "Claude", "nav.iletisim": "İletişim",

    "hero.etiket": "AKILLI KOMBİ TERMOSTATI · TÜRKİYE",
    "hero.baslik_html": "Sıcaklık, <em>tam</em> istediğiniz gibi.",
    "hero.metin": "NeraHom; pilli bir oda sensörü, kombinize bağlanan bir röle ve mobil uygulamadan oluşan akıllı bir ısıtma sistemi. Donanımı, gömülü yazılımı, sunucusu ve uygulaması tek ekipte, Türkiye'de geliştiriliyor.",
    "hero.cta1": "Ekranı deneyin", "hero.cta2": "Bize yazın",
    "hero.olcu": "NERAHOM SENSÖR · 87 × 96 × 28 MM · 1.8″ TFT · EC11 ENKODER",
    "hero.alt": "Duvara monte NeraHom oda sensörü: ekranında sıcaklık, nem ve eşik değeri; sağda kırmızı ayar düğmesi",
    "hero.c1": "İnternetsiz çalışır (ESP-NOW)", "hero.c2": "Uzaktan güncelleme (OTA)",
    "hero.c3": "iOS ve Android uygulaması", "hero.c4": "Kombiye kuru kontak",

    "ekran.no": "01 — EKRAN",
    "ekran.baslik": "Düğmeyi çevirin, kombi cevap versin.",
    "ekran.metin_html": "Bu ekran bir görsel değil. Cihaz yazılımındaki çizim kodu tarayıcıya birebir aktarıldı: aynı 128 × 160 piksel, aynı 5 × 7 font, aynı renkler. Düğmeyi sürükleyin, üzerinde kaydırın ya da ok tuşlarını kullanın. Kombi kararı cihazdaki kuralla verilir: <code>sıcaklık &lt; eşik − 0,5 °C</code> ise kombi açılır.",
    "ekran.oda": "Oda", "ekran.esik": "Eşik", "ekran.kombi": "Kombi",
    "ekran.acik": "AÇIK", "ekran.kapali": "KAPALI",
    "ekran.mod": "Bağlantı", "ekran.srv": "Sunucu (SRV)", "ekran.now": "Yerel ESP-NOW (NOW)",
    "ekran.koruyucu": "Ekran koruyucu", "ekran.uyandir": "Ekranı uyandır",
    "ekran.govde": "Gövde", "ekran.kirmizi": "Kırmızı", "ekran.krem": "Krem", "ekran.antrasit": "Antrasit",
    "ekran.azalt": "Eşiği 0,5 °C azalt", "ekran.artir": "Eşiği 0,5 °C artır",
    "ekran.dugme": "Hedef sıcaklık düğmesi",
    "ekran.alt": "NeraHom sensörünün önden görünümü",
    "ekran.not_html": "Oda sıcaklığı simüle edilir: kombi açıkken yavaşça ısınır, kapalıyken soğur. Cihaz 60 sn hareketsizlikte ekran koruyucuya geçer; burada bu süre 12 sn. Kaynak: <code>ui_manager.cpp → drawStatic(), drawScreensaver()</code>",

    "sistem.no": "02 — SİSTEM",
    "sistem.baslik": "Üç parça, tek bir sıcaklık.",
    "sistem.metin": "Sensör odayı ölçer, röle kombiyi sürer, uygulama her şeyi cebinize taşır. Aralarındaki bağlantı internete muhtaç değil.",
    "sistem.aile_alt": "NeraHom röle kutusu ve oda sensörü duvarda yan yana",
    "sensor.etiket": "ODA SENSÖRÜ", "sensor.surum": "v2 · tasarım",
    "sensor.baslik": "Duvarda sade, içeride akıllı.",
    "sensor.l1": "Li-ion pil, USB-C ile şarj",
    "sensor.l2": "1.8″ ekran normalde kapalı, düğmeye basınca açılır",
    "sensor.l3": "Sıcaklık ve nem: AHT20 + BMP280",
    "sensor.l4": "EC11 düğmeyle 0,5 °C adımlarla ayar",
    "sensor.renk": "Renk çalışmaları",
    "sensor.alt": "NeraHom oda sensörü",
    "role.etiket": "RÖLE · GATEWAY", "role.surum": "v2 · tasarım",
    "role.baslik": "Kombinin yanında, şebekeden beslenir.",
    "role.l1": "Kombinin oda termostatı girişine kuru kontak (NO/COM/NC)",
    "role.l2": "Sunucuya Wi-Fi + MQTT, sensöre ESP-NOW ile bağlanır",
    "role.l3": "HLK-PM01 besleme; sigorta ve varistörle korunan 220 V bölümü",
    "role.l4": "Güç, ağ ve röle LED'leri; MOD butonu",
    "role.alt": "NeraHom röle kutusu; üç durum LED'i ve kırmızı MOD butonu",
    "app.etiket": "MOBİL UYGULAMA", "app.surum": "v1 · Flutter",
    "app.baslik": "Evden uzaktayken de.",
    "app.l1": "Anlık sıcaklık, nem ve kombi durumu",
    "app.l2": "16–30 °C arası hedef, 0,5 °C adım",
    "app.l3": "Haftalık program: her gün için saat + sıcaklık",
    "app.l4": "15 dk – 6 sa sıcaklık ve nem grafiği",
    "app.l5": "6 haneli kodla cihaz eşleştirme",
    "app.alt": "NeraHom uygulama simgesi",


    "nav.yazilim": "Yazılım",
    "nav.ozellikler": "Özellikler",
    "nav.uygulama": "Uygulama",
    "m.no": "03 — MOBİL UYGULAMA",
    "m.baslik": "Kombiniz cebinizde.",
    "m.metin": "iOS ve Android için Flutter ile yazılan NeraHom uygulaması anlık durumu, hedef sıcaklığı ve haftalık programı tek yerde toplar. Sıradaki adım: Claude destekli asistan ile kombinize Türkçe konuşarak komut vermek.",
    "m.salon": "Salon",
    "m.cevrimici": "Çevrimiçi",
    "m.hedef": "Hedef",
    "m.kombiacik": "Kombi açık",
    "m.nem": "Nem %48",
    "m.grafik": "Son 6 saat · sıcaklık / nem",
    "m.program": "Haftalık program",
    "m.g1": "Pzt",
    "m.g2": "Sal",
    "m.g3": "Çar",
    "m.g4": "Per",
    "m.g5": "Cum",
    "m.g6": "Cmt",
    "m.g7": "Paz",
    "m.kural": "+ Kural ekle",
    "m.asistan": "Asistan",
    "m.s1": "Akşam 7'de salonu 22 derece yap",
    "m.eylem": "ÖNERİLEN İŞLEM",
    "m.eylemd": "Bugün 19:00 · Salon → 22,0 °C",
    "m.onayla": "Onayla",
    "m.vazgec": "Vazgeç",
    "m.s2": "Onaylandı. Saat 19:00'da salon 22,0 °C'ye ayarlanacak.",
    "m.s3": "Hafta sonu sabahları biraz daha sıcak olsun",
    "m.s4": "Cumartesi ve pazar 09:00 kuralını 22,0 → 22,5 °C yapayım mı?",
    "m.yaz": "Bir şey yazın…",
    "m.c1": "Anlık durum, hedef sıcaklık ve grafik",
    "m.c2": "Gün gün haftalık program",
    "m.c3": "Claude ile doğal dilde komut (geliştiriliyor)",
    "m.o1": "Anlık sıcaklık, nem ve kombi durumu",
    "m.o2": "16–30 °C hedef, 0,5 °C adım",
    "m.o3": "Haftalık program",
    "m.o4": "15 dk – 6 sa grafik",
    "m.o5": "6 haneli kodla eşleştirme",
    "m.o6": "Açık / koyu tema",
    "m.o7": "Claude asistanı · geliştiriliyor",
    "m.not": "Ekranlar tasarım önizlemesidir. Asistan ekranı geliştirme aşamasında; komutlar uygulanmadan önce sunucuda doğrulanır ve gerekirse onayınız istenir.",

    "yaz.no": "04 — YAZILIM",
    "yaz.baslik": "Akıllı olan kutu değil, içindeki yazılım.",
    "yaz.metin": "Sensörün gömülü yazılımı, rölenin karar mantığı, MQTT sunucusu ve mobil uygulama birlikte tasarlandı. Öne çıkan özellikler:",
    "yaz.1e": "BAĞLANTI",
    "yaz.1b": "İnternetsiz çalışma",
    "yaz.1m": "Sunucuya ulaşılamazsa sensör kendiliğinden yerel moda (NOW) geçer ve kombiyi ESP-NOW üzerinden doğrudan yönetir. Bağlantı dönünce sunucu moduna (SRV) geri döner.",
    "yaz.2e": "CANLI VERİ",
    "yaz.2b": "MQTT ile anlık durum",
    "yaz.2m": "Sıcaklık, nem ve kombi durumu uygulamaya anında düşer. Komutlar QoS 1 ve retained gönderilir; cihaz yeniden bağlandığında son hedef sıcaklığı kendisi alır. HTTP yedek kanal olarak durur.",
    "yaz.3e": "PROGRAM",
    "yaz.3b": "Haftalık program ve geçici ayar",
    "yaz.3m": "Her gün için saat + sıcaklık kuralları. Program çalışırken elle yapılan değişiklik yalnızca o zaman dilimi bitene kadar geçerlidir, sonra program kaldığı yerden devam eder.",
    "yaz.4e": "GÜNCELLEME",
    "yaz.4b": "Kablosuz güncelleme (OTA)",
    "yaz.4m": "Yeni yazılım sürümleri cihaz menüsünden kablosuz yüklenir; cihazı duvardan sökmeye gerek kalmaz.",
    "yaz.5e": "CİHAZ MENÜSÜ",
    "yaz.5b": "Düğmeden tam kontrol",
    "yaz.5m": "Düğmeye basınca açılan menüden eşleştirme, bağlantı modu, ±5 °C sıcaklık kalibrasyonu, Wi-Fi sıfırlama, OTA ve yeniden başlatma yapılır.",
    "yaz.6e": "GÜVENLİK",
    "yaz.6b": "Eşleştirme ve hesap güvenliği",
    "yaz.6m": "Cihazlar hesaba 6 haneli kodla eklenir. Uygulama ile sunucu arası JWT kimlik doğrulamasıyla korunur; her istekte cihazın o kullanıcıya ait olduğu kontrol edilir.",
    "yaz.7e": "KARAR MANTIĞI",
    "yaz.7b": "Karar cihazda",
    "yaz.7m": "v2'de kombiyi açıp kapatma kararını röle verir: histerezis, en kısa çalışma/bekleme süreleri ve haftalık program cihazın kendi belleğinde; saat NTP ile tutulur.",
    "yaz.8e": "GÜVENLİ VARSAYILAN",
    "yaz.8b": "Arızada kombi kapanır",
    "yaz.8m": "v2 tasarım hedefi: sensörden 10 dakika veri gelmezse röle kombiyi kapatır; elle çalıştırma en fazla 2 saat sürer.",
    "tek.no": "05 — TEKNİK ÖZELLİKLER",
    "tek.baslik": "Rakamlarla NeraHom.",
    "tek.metin": "v1: çalışan prototip · v2: tasarımı tamamlanan sürüm.",
    "tek.s": "Oda sensörü",
    "tek.s1d": "İşlemci",
    "tek.s1v": "ESP32-C3 (v1) · ESP32-C6 (v2)",
    "tek.s2d": "Ekran",
    "tek.s2v": "1.8″ TFT, ST7735, 128 × 160 piksel",
    "tek.s3d": "Ölçüm",
    "tek.s3v": "Sıcaklık ve nem · DHT22 (v1) · AHT20 + BMP280 (v2)",
    "tek.s4d": "Kontrol",
    "tek.s4v": "EC11 döner enkoder + basma butonu",
    "tek.s5d": "Ayar aralığı",
    "tek.s5v": "18–30 °C, 0,5 °C adım",
    "tek.s6d": "Kalibrasyon",
    "tek.s6v": "±5,0 °C sıcaklık ofseti",
    "tek.s7d": "Güç",
    "tek.s7v": "USB 5 V (v1) · Li-ion pil + USB-C şarj (v2)",
    "tek.s8d": "Kutu",
    "tek.s8v": "87 × 96 × 28 mm",
    "tek.r": "Röle · gateway",
    "tek.r1d": "İşlemci",
    "tek.r1v": "ESP8266 (v1) · ESP32-C6 (v2)",
    "tek.r2d": "Kombi bağlantısı",
    "tek.r2v": "Kuru kontak röle, NO / COM / NC",
    "tek.r3d": "Besleme",
    "tek.r3v": "220 V AC, HLK-PM01 · sigorta + varistör (v2)",
    "tek.r4d": "Göstergeler",
    "tek.r4v": "Güç, ağ ve röle LED'leri",
    "tek.r5d": "MOD butonu",
    "tek.r5v": "Elle çalıştırma, eşleştirme sıfırlama, OTA, fabrika ayarı",
    "tek.r6d": "Kutu",
    "tek.r6v": "97 × 92 × 28 mm",
    "tek.b": "Bağlantı ve yazılım",
    "tek.b1d": "Sensör ↔ röle",
    "tek.b1v": "ESP-NOW, Wi-Fi kanalını otomatik bulur",
    "tek.b2d": "Cihaz ↔ sunucu",
    "tek.b2v": "Wi-Fi · MQTT (QoS 1, retained) · HTTP yedek",
    "tek.b3d": "Uygulama ↔ sunucu",
    "tek.b3v": "REST API + JWT · canlı veri MQTT/WebSocket",
    "tek.b4d": "Program",
    "tek.b4v": "Haftalık, gün başına saat + sıcaklık",
    "tek.b5d": "Geçmiş",
    "tek.b5v": "15 dk – 6 sa sıcaklık ve nem grafiği",
    "tek.b6d": "Uygulama",
    "tek.b6v": "Flutter · iOS ve Android · açık/koyu tema",
    "tek.b7d": "Güncelleme",
    "tek.b7v": "OTA (kablosuz)",
    "tek.y1": "Donanım",
    "tek.y2": "Gömülü yazılım",
    "tek.y3": "Sunucu",
    "tek.y4": "Uygulama",
    "tek.y5": "Yapay zekâ",
    "tek.d1": "ESP32 · EasyEDA · 3D baskı kutu",
    "tek.d2": "C++ (Arduino) · ESP-NOW · MQTT · OTA",
    "tek.d3": "Python · Flask · SQLite · Mosquitto MQTT",
    "tek.d4": "Flutter · iOS ve Android",
    "tek.d5": "Claude API · tool use (geliştiriliyor)",

    "claude.no": "06 — CLAUDE", "claude.etiket": "GELİŞTİRİLİYOR",
    "claude.baslik": "Termostata derdinizi anlatın.",
    "claude.metin_html": "Uygulamaya Anthropic'in <strong>Claude</strong> modeliyle çalışan bir komut asistanı ekliyoruz. “Akşam 7'de salonu 22 derece yap” gibi bir cümle, Claude API'nin araç kullanımı (<em>tool use</em>) ile yapılandırılmış bir komuta dönüşür. Model kombiyi hiçbir zaman doğrudan sürmez: her komut sunucuda yetki, 16–30 °C sınırı ve zamanlama kurallarıyla doğrulandıktan sonra cihaza gider.",
    "claude.dene": "Bir örnek seçin",
    "claude.bos": "Bir örnek seçtiğinizde konuşma burada görünecek.",
    "claude.arac": "araç çağrısı", "claude.sonuc": "sunucu yanıtı",
    "claude.not": "Bu bölüm etkileşimli bir prototiptir: yanıtlar önceden hazırlanmıştır, canlı API çağrısı yapılmaz.",
    "claude.siz": "Siz", "claude.asistan": "NeraHom asistanı",


    "yol.no": "07 — YOL HARİTASI",
    "yol.baslik": "Neredeyiz?",
    "yol.1e": "ŞİMDİ", "yol.1b": "v1 prototip",
    "yol.1m": "ESP32-C3 sensör ve ESP8266 röle; Flask + MQTT sunucu; haftalık program ve uzaktan kontrollü Flutter uygulaması.",
    "yol.2e": "SIRADAKİ", "yol.2b": "v2 donanım",
    "yol.2m": "Pilli sensör ve gateway röle. Donanım tasarımı tamamlandı (Ekim 2026); sırada prototip üretimi ve saha testleri.",
    "yol.3e": "SONRA", "yol.3b": "Daha akıllı bir ev",
    "yol.3m": "Claude ile doğal dilde kontrol; akıllı priz, gaz, su kaçağı ve kapı-pencere sensörleri.",

    "iletisim.no": "08 — İLETİŞİM",
    "iletisim.baslik": "Merhaba deyin.",
    "iletisim.metin": "NeraHom, 2025'te Türkiye'de kurulan bir akıllı ev girişimi. Pilot kullanıcı olmak, iş birliği ya da yatırım için bize yazın.",
    "iletisim.kurucu": "Kurucu: İlker Dizbay — gömülü sistemler, donanım ve yazılım",

    "alt.telif": "© 2026 NeraHom. Türkiye'de tasarlandı.",
    "alt.not": "Ürün görselleri cihazın 3D CAD modellerinden render edilmiştir; ekran görüntüleri cihaz yazılımının çizim koduyla üretilir.",
  },

  en: {
    "meta.title": "NeraHom — Smart boiler thermostat",
    "meta.desc": "A smart heating system — battery room sensor, boiler relay and mobile app — that keeps working when the internet doesn't.",
    "nav.ekran": "Display", "nav.sistem": "System", "nav.claude": "Claude", "nav.iletisim": "Contact",

    "hero.etiket": "SMART BOILER THERMOSTAT · TÜRKİYE",
    "hero.baslik_html": "Warmth, <em>exactly</em> how you like it.",
    "hero.metin": "NeraHom is a smart heating system: a battery-powered room sensor, a relay that wires into your combi boiler, and a mobile app. Hardware, firmware, server and app are all built by one team in Türkiye.",
    "hero.cta1": "Try the display", "hero.cta2": "Get in touch",
    "hero.olcu": "NERAHOM SENSOR · 87 × 96 × 28 MM · 1.8″ TFT · EC11 ENCODER",
    "hero.alt": "Wall-mounted NeraHom room sensor showing temperature, humidity and setpoint, with a red control dial",
    "hero.c1": "Works offline (ESP-NOW)", "hero.c2": "Over-the-air updates",
    "hero.c3": "iOS & Android app", "hero.c4": "Dry-contact boiler wiring",

    "ekran.no": "01 — DISPLAY",
    "ekran.baslik": "Turn the dial. The boiler answers.",
    "ekran.metin_html": "This isn't a picture. The drawing code from the device firmware runs right here in your browser: same 128 × 160 pixels, same 5 × 7 font, same colours. Drag the dial, scroll on it, or use the arrow keys. The boiler decision follows the on-device rule: it turns on when <code>temperature &lt; setpoint − 0.5 °C</code>.",
    "ekran.oda": "Room", "ekran.esik": "Setpoint", "ekran.kombi": "Boiler",
    "ekran.acik": "ON", "ekran.kapali": "OFF",
    "ekran.mod": "Link", "ekran.srv": "Server (SRV)", "ekran.now": "Local ESP-NOW (NOW)",
    "ekran.koruyucu": "Screensaver", "ekran.uyandir": "Wake display",
    "ekran.govde": "Body", "ekran.kirmizi": "Red", "ekran.krem": "Cream", "ekran.antrasit": "Anthracite",
    "ekran.azalt": "Lower setpoint by 0.5 °C", "ekran.artir": "Raise setpoint by 0.5 °C",
    "ekran.dugme": "Setpoint dial",
    "ekran.alt": "Front view of the NeraHom sensor",
    "ekran.not_html": "Room temperature is simulated: it rises while the boiler runs and falls when it stops. The device switches to its screensaver after 60 s idle; here it's 12 s. Source: <code>ui_manager.cpp → drawStatic(), drawScreensaver()</code>",

    "sistem.no": "02 — SYSTEM",
    "sistem.baslik": "Three parts, one temperature.",
    "sistem.metin": "The sensor measures the room, the relay drives the boiler, the app puts it all in your pocket. The link between them doesn't depend on the internet.",
    "sistem.aile_alt": "NeraHom relay box and room sensor side by side on a wall",
    "sensor.etiket": "ROOM SENSOR", "sensor.surum": "v2 · design",
    "sensor.baslik": "Quiet on the wall, smart inside.",
    "sensor.l1": "Li-ion battery, USB-C charging",
    "sensor.l2": "1.8″ display stays off until you press the dial",
    "sensor.l3": "Temperature & humidity: AHT20 + BMP280",
    "sensor.l4": "EC11 dial, 0.5 °C steps",
    "sensor.renk": "Colour studies",
    "sensor.alt": "NeraHom room sensor",
    "role.etiket": "RELAY · GATEWAY", "role.surum": "v2 · design",
    "role.baslik": "Sits by the boiler, powered from the mains.",
    "role.l1": "Dry contact to the boiler's room-thermostat input (NO/COM/NC)",
    "role.l2": "Talks to the server over Wi-Fi + MQTT, to the sensor over ESP-NOW",
    "role.l3": "HLK-PM01 supply; 220 V section protected by fuse and varistor",
    "role.l4": "Power, network and relay LEDs; MODE button",
    "role.alt": "NeraHom relay box with three status LEDs and a red MODE button",
    "app.etiket": "MOBILE APP", "app.surum": "v1 · Flutter",
    "app.baslik": "Even when you're away.",
    "app.l1": "Live temperature, humidity and boiler state",
    "app.l2": "Setpoint from 16 to 30 °C in 0.5 °C steps",
    "app.l3": "Weekly schedule: time + temperature for each day",
    "app.l4": "Temperature & humidity charts, 15 min – 6 h",
    "app.l5": "Pair devices with a 6-digit code",
    "app.alt": "NeraHom app icon",


    "nav.yazilim": "Software",
    "nav.ozellikler": "Specs",
    "nav.uygulama": "App",
    "m.no": "03 — MOBILE APP",
    "m.baslik": "Your boiler, in your pocket.",
    "m.metin": "The NeraHom app, built with Flutter for iOS and Android, brings live status, setpoint and weekly schedule into one place. Next up: a Claude-powered assistant that lets you talk to your boiler in plain language.",
    "m.salon": "Living room",
    "m.cevrimici": "Online",
    "m.hedef": "Target",
    "m.kombiacik": "Boiler on",
    "m.nem": "Humidity 48%",
    "m.grafik": "Last 6 hours · temperature / humidity",
    "m.program": "Weekly schedule",
    "m.g1": "Mon",
    "m.g2": "Tue",
    "m.g3": "Wed",
    "m.g4": "Thu",
    "m.g5": "Fri",
    "m.g6": "Sat",
    "m.g7": "Sun",
    "m.kural": "+ Add rule",
    "m.asistan": "Assistant",
    "m.s1": "Set the living room to 22° at 7 pm",
    "m.eylem": "PROPOSED ACTION",
    "m.eylemd": "Today 19:00 · Living room → 22.0 °C",
    "m.onayla": "Confirm",
    "m.vazgec": "Cancel",
    "m.s2": "Confirmed. The living room will be set to 22.0 °C at 19:00.",
    "m.s3": "Make weekend mornings a bit warmer",
    "m.s4": "Shall I change the Saturday and Sunday 09:00 rule from 22.0 to 22.5 °C?",
    "m.yaz": "Type something…",
    "m.c1": "Live status, setpoint and chart",
    "m.c2": "Day-by-day weekly schedule",
    "m.c3": "Plain-language commands with Claude (in development)",
    "m.o1": "Live temperature, humidity and boiler state",
    "m.o2": "16–30 °C setpoint, 0.5 °C steps",
    "m.o3": "Weekly schedule",
    "m.o4": "15 min – 6 h charts",
    "m.o5": "6-digit pairing",
    "m.o6": "Light / dark theme",
    "m.o7": "Claude assistant · in development",
    "m.not": "Screens are design previews. The assistant is in development; commands are validated on our server before they run, and you're asked to confirm when needed.",

    "yaz.no": "04 — SOFTWARE",
    "yaz.baslik": "The smart part isn't the box. It's the software.",
    "yaz.metin": "Sensor firmware, relay logic, MQTT server and mobile app were designed together. Highlights:",
    "yaz.1e": "CONNECTIVITY",
    "yaz.1b": "Works without internet",
    "yaz.1m": "If the server can't be reached, the sensor switches to local mode (NOW) on its own and drives the boiler directly over ESP-NOW. When the connection returns it goes back to server mode (SRV).",
    "yaz.2e": "LIVE DATA",
    "yaz.2b": "Real-time state over MQTT",
    "yaz.2m": "Temperature, humidity and boiler state reach the app instantly. Commands are sent with QoS 1 and retained, so a reconnecting device picks up the latest setpoint by itself. HTTP stays as a fallback channel.",
    "yaz.3e": "SCHEDULING",
    "yaz.3b": "Weekly schedule with temporary override",
    "yaz.3m": "Time + temperature rules for every day. A manual change while the schedule runs lasts only until the current time block ends; then the schedule resumes.",
    "yaz.4e": "UPDATES",
    "yaz.4b": "Over-the-air updates",
    "yaz.4m": "New firmware installs wirelessly from the device menu — no need to take the device off the wall.",
    "yaz.5e": "DEVICE MENU",
    "yaz.5b": "Full control from the dial",
    "yaz.5m": "Press the dial to open a menu for pairing, link mode, ±5 °C temperature calibration, Wi-Fi reset, OTA and restart.",
    "yaz.6e": "SECURITY",
    "yaz.6b": "Pairing and account security",
    "yaz.6m": "Devices join an account with a 6-digit code. App-to-server traffic is protected by JWT authentication, and every request checks that the device belongs to that user.",
    "yaz.7e": "CONTROL LOGIC",
    "yaz.7b": "Decisions on the device",
    "yaz.7m": "In v2 the relay makes the on/off call itself: hysteresis, minimum run/rest times and the weekly schedule live in its own memory, with time kept over NTP.",
    "yaz.8e": "FAIL-SAFE",
    "yaz.8b": "Boiler off on failure",
    "yaz.8m": "v2 design target: if the sensor goes quiet for 10 minutes the relay turns the boiler off; a manual override lasts at most 2 hours.",
    "tek.no": "05 — SPECIFICATIONS",
    "tek.baslik": "NeraHom in numbers.",
    "tek.metin": "v1: working prototype · v2: completed design.",
    "tek.s": "Room sensor",
    "tek.s1d": "MCU",
    "tek.s1v": "ESP32-C3 (v1) · ESP32-C6 (v2)",
    "tek.s2d": "Display",
    "tek.s2v": "1.8″ TFT, ST7735, 128 × 160 pixels",
    "tek.s3d": "Sensing",
    "tek.s3v": "Temperature & humidity · DHT22 (v1) · AHT20 + BMP280 (v2)",
    "tek.s4d": "Control",
    "tek.s4v": "EC11 rotary encoder + push button",
    "tek.s5d": "Setpoint range",
    "tek.s5v": "18–30 °C, 0.5 °C steps",
    "tek.s6d": "Calibration",
    "tek.s6v": "±5.0 °C temperature offset",
    "tek.s7d": "Power",
    "tek.s7v": "USB 5 V (v1) · Li-ion battery + USB-C charging (v2)",
    "tek.s8d": "Enclosure",
    "tek.s8v": "87 × 96 × 28 mm",
    "tek.r": "Relay · gateway",
    "tek.r1d": "MCU",
    "tek.r1v": "ESP8266 (v1) · ESP32-C6 (v2)",
    "tek.r2d": "Boiler wiring",
    "tek.r2v": "Dry-contact relay, NO / COM / NC",
    "tek.r3d": "Supply",
    "tek.r3v": "220 V AC, HLK-PM01 · fuse + varistor (v2)",
    "tek.r4d": "Indicators",
    "tek.r4v": "Power, network and relay LEDs",
    "tek.r5d": "MODE button",
    "tek.r5v": "Manual run, pairing reset, OTA, factory reset",
    "tek.r6d": "Enclosure",
    "tek.r6v": "97 × 92 × 28 mm",
    "tek.b": "Connectivity & software",
    "tek.b1d": "Sensor ↔ relay",
    "tek.b1v": "ESP-NOW, finds the Wi-Fi channel automatically",
    "tek.b2d": "Device ↔ server",
    "tek.b2v": "Wi-Fi · MQTT (QoS 1, retained) · HTTP fallback",
    "tek.b3d": "App ↔ server",
    "tek.b3v": "REST API + JWT · live data over MQTT/WebSocket",
    "tek.b4d": "Schedule",
    "tek.b4v": "Weekly, time + temperature per day",
    "tek.b5d": "History",
    "tek.b5v": "Temperature & humidity charts, 15 min – 6 h",
    "tek.b6d": "App",
    "tek.b6v": "Flutter · iOS & Android · light/dark theme",
    "tek.b7d": "Updates",
    "tek.b7v": "OTA (wireless)",
    "tek.y1": "Hardware",
    "tek.y2": "Firmware",
    "tek.y3": "Server",
    "tek.y4": "App",
    "tek.y5": "AI",
    "tek.d1": "ESP32 · EasyEDA · 3D-printed enclosures",
    "tek.d2": "C++ (Arduino) · ESP-NOW · MQTT · OTA",
    "tek.d3": "Python · Flask · SQLite · Mosquitto MQTT",
    "tek.d4": "Flutter · iOS & Android",
    "tek.d5": "Claude API · tool use (in development)",

    "claude.no": "06 — CLAUDE", "claude.etiket": "IN DEVELOPMENT",
    "claude.baslik": "Just tell your thermostat.",
    "claude.metin_html": "We're adding a command assistant powered by Anthropic's <strong>Claude</strong> to the app. A sentence like “Set the living room to 22 degrees at 7 pm” becomes a structured command through the Claude API's <em>tool use</em>. The model never drives the boiler directly: every command is checked on our server — ownership, a 16–30 °C limit and scheduling rules — before it reaches the device.",
    "claude.dene": "Pick an example",
    "claude.bos": "Pick an example and the conversation will appear here.",
    "claude.arac": "tool call", "claude.sonuc": "server result",
    "claude.not": "This is an interactive prototype: responses are pre-written and no live API call is made.",
    "claude.siz": "You", "claude.asistan": "NeraHom assistant",


    "yol.no": "07 — ROADMAP",
    "yol.baslik": "Where we are",
    "yol.1e": "NOW", "yol.1b": "v1 prototype",
    "yol.1m": "ESP32-C3 sensor and ESP8266 relay; Flask + MQTT server; Flutter app with weekly schedules and remote control.",
    "yol.2e": "NEXT", "yol.2b": "v2 hardware",
    "yol.2m": "Battery sensor and gateway relay. Hardware design completed (October 2026); prototype build and field tests next.",
    "yol.3e": "LATER", "yol.3b": "A smarter home",
    "yol.3m": "Natural-language control with Claude; smart plug, gas, water-leak and door/window sensors.",

    "iletisim.no": "08 — CONTACT",
    "iletisim.baslik": "Say hello.",
    "iletisim.metin": "NeraHom is a smart-home startup founded in Türkiye in 2025. Write to us about pilots, partnerships or investment.",
    "iletisim.kurucu": "Founder: İlker Dizbay — embedded systems, hardware and software",

    "alt.telif": "© 2026 NeraHom. Designed in Türkiye.",
    "alt.not": "Product images are rendered from the device's 3D CAD models; screen images are generated by the device firmware's drawing code.",
  },
};

// Claude bölümündeki örnek konuşmalar. `uygula` demo termostatını günceller.
export const ORNEKLER = [
  {
    kimlik: "aksam",
    soru: { tr: "Akşam 7'de salonu 22 derece yap", en: "Set the living room to 22° at 7 pm" },
    adimlar: () => [
      { arac: "schedule_once", girdi: { device: "salon", at: "19:00", target_c: 22.0 }, sonuc: { ok: true, scheduled_for: "19:00", target_c: 22.0 } },
    ],
    yanit: () => ({ tr: "Tamam. Bugün 19:00'da Salon 22,0 °C'ye ayarlanacak.", en: "Done. The living room will be set to 22.0 °C today at 19:00." }),
  },
  {
    kimlik: "usudum",
    soru: { tr: "Biraz üşüdüm", en: "I'm a bit cold" },
    adimlar: (d) => {
      const yeni = Math.min(30, d.thresh + 1);
      return [
        { arac: "get_status", girdi: { device: "salon" }, sonuc: { temp_c: +d.temp.toFixed(1), target_c: d.thresh, boiler: d.acik ? "on" : "off" } },
        { arac: "set_target_temperature", girdi: { device: "salon", target_c: yeni }, sonuc: { ok: true, target_c: yeni } },
      ];
    },
    uygula: (d) => ({ thresh: Math.min(30, d.thresh + 1) }),
    yanit: (d, once) => {
      const yeni = Math.min(30, once.thresh + 1);
      const tr = (v) => v.toFixed(1).replace(".", ",");
      return {
        tr: `Salonun hedefini ${tr(once.thresh)} °C → ${tr(yeni)} °C olarak güncelledim. Yukarıdaki ekran da değişti.`,
        en: `I raised the living room from ${once.thresh.toFixed(1)} to ${yeni.toFixed(1)} °C. The display above has updated too.`,
      };
    },
  },
  {
    kimlik: "haftaici",
    soru: { tr: "Hafta içi sabah 6:30'da 21 derece olsun", en: "Weekdays at 6:30 am, make it 21°" },
    adimlar: () => [
      { arac: "add_weekly_entry", girdi: { device: "salon", days: [0, 1, 2, 3, 4], time: "06:30", target_c: 21.0 }, sonuc: { ok: true, entries_added: 5 } },
    ],
    yanit: () => ({ tr: "Pazartesi–Cuma 06:30 → 21,0 °C programa eklendi.", en: "Added Monday–Friday 06:30 → 21.0 °C to the weekly schedule." }),
  },
  {
    kimlik: "kirk",
    soru: { tr: "Kombiyi 40 dereceye ayarla", en: "Set the boiler to 40 degrees" },
    adimlar: () => [
      { arac: "set_target_temperature", girdi: { device: "salon", target_c: 40.0 }, sonuc: { error: "out_of_range", min_c: 16, max_c: 30 }, hata: true },
    ],
    yanit: () => ({ tr: "Bunu yapamam: hedef sıcaklık en fazla 30 °C olabilir. 30 °C'ye ayarlamamı ister misiniz?", en: "I can't do that — the setpoint can be at most 30 °C. Shall I set it to 30 °C instead?" }),
  },
];
